### ISSUE TITLE
Copy/paste broken

### ISSUE THREAD

**Issue by joshzana** [wangyanxing/buck_idea_plugin#1]
Love the plugin, but after installing it and opening an android project, copy/paste in a java or xml file is is a no-op.  With keyboard or with right click.  I'm on a mac with android studio 1.3 final.

**Comment by wangyanxing** [comment]
I've fixed the copy-paste bug, could you download and try again?
Link: https://github.com/wangyanxing/buck_idea_plugin/blob/master/Buck.zip?raw=true

**Comment by joshzana** [comment]
That worked.  Thanks!
