### ISSUE TITLE
Argument for @NotNull parameter 'exePath' of com/intellij/execution/configurations/GeneralCommandLine.setExePath must not be null

### ISSUE THREAD

**Issue by rohitiskul** [wangyanxing/buck_idea_plugin#3]
Keep getting this error when try to run the build using blue play button. 
I have checked the file BuckExecutableDetector.java, it only checks the executable in /usr/\* paths. My buck home is in /Documents. I am not sure but it might be the issue.

**Comment by wangyanxing** [comment]
Could you try set your buck executable path in settings? Let's see if it works

**Comment by rohitiskul** [comment]
Yes, that works. Thanks.
Flow is ->
Studio Preferences -> Tools -> Buck -> set executable path.

But my suggestion would be plugin should by default consider /usr/\* paths as well as BUCK_HOME or something like that from .bash_profile.

**Comment by wangyanxing** [comment]
Yeah, good suggestion! thanks!
